name: inter_knot
description: 绳网是一个游戏、技术交流平台
publish_to: none
version: 2.4.1+3
repository: https://github.com/share121/inter_knot

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  url_launcher: ^6.3.0
  window_manager: ^0.4.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  waterfall_flow: ^3.0.3
  dio: ^5.6.0
  shared_preferences: ^2.3.2
  dart_jsonwebtoken: ^2.14.0
  flutter_gen: ^5.6.0
  html: ^0.15.4
  flutter_widget_from_html: ^0.15.2
  fwfh_cached_network_image: ^0.14.3
  fwfh_svg: ^0.8.3
  fwfh_url_launcher: ^0.9.1
  cached_network_image: ^3.4.1
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.0.2
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.8

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/icon.png
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

msix_config:
  display_name: 绳网
  publisher_display_name: share121
  identity_name: com.share121.inter-knot
  msix_version: 1.0.0.0
  logo_path: assets/images/icon.png
  capabilities: internetClient
  languages: zh-CN, en-US

false_secrets:
  - assets/private_key.pem
